// Generated by kea-typegen on Sat, 21 May 2022 16:31:56 GMT. DO NOT EDIT THIS FILE MANUALLY.

import { Logic } from 'kea'

export interface blogLogicType extends Logic {
    actionCreators: {
        loading: (params: any) => ({
            type: "loading (app.testLogic)";
            payload: {
                params: any;
            };
        });
    };
    actionKeys: {
        "loading (app.testLogic)": "loading";
    };
    actionTypes: {
        loading: "loading (app.testLogic)";
    };
    actions: {
        loading: (params: any) => void;
    };
    defaults: {
        name: string;
    };
    events: {};
    key: undefined;
    listeners: {};
    path: [
        "app",
        "testLogic"
    ];
    pathString: "app.testLogic";
    props: Record<string, unknown>;
    reducer: (state: any, action: any, fullState: any) => {
        name: string;
    };
    reducers: {
        name: (state: string, action: any, fullState: any) => string;
    };
    selector: (state: any) => {
        name: string;
    };
    selectors: {
        name: (state: any, props?: any) => string;
    };
    sharedListeners: {};
    values: {
        name: string;
    };
    _isKea: true;
    _isKeaWithKey: false;
}